CREATE TABLE partition_metadata(
  OWNER                  VARCHAR2(30) NOT NULL,
  TABLE_NAME             VARCHAR2(30) NOT NULL,
  PARTITION_FREQUENCY    VARCHAR2(30) NOT NULL,
  PARTITION_NAME_FORMAT  VARCHAR2(30) NOT NULL,
  PARTITION_TS_FORMAT    VARCHAR2(30) NOT NULL,
  FIRST_PARTITION_NAME   VARCHAR2(30) NOT NULL,
  MAXVAL_PARTITION_NAME  VARCHAR2(30) NOT NULL,
  MAXVAL_TS_NAME_FORMAT  VARCHAR2(30) NOT NULL,
  NUM_ADVANCE_PARTITIONS NUMBER       DEFAULT 1 NOT NULL,       
  ACTIVE_RECORD_FLAG     VARCHAR2(1)  DEFAULT 'Y' NOT NULL,
  DW_UPDATED_BY          VARCHAR2(30) NOT NULL,
  DW_LAST_UPDATED        DATE         NOT NULL
);

INSERT INTO PARTITION_METADATA (OWNER,TABLE_NAME,PARTITION_FREQUENCY,PARTITION_NAME_FORMAT,PARTITION_TS_FORMAT,FIRST_PARTITION_NAME,MAXVAL_PARTITION_NAME,MAXVAL_TS_NAME_FORMAT,NUM_ADVANCE_PARTITIONS,ACTIVE_RECORD_FLAG,DW_UPDATED_BY,DW_LAST_UPDATED)
 VALUES ('DWH','SALES','DAILY','P{yyyy}{mm}{dd}','DWH_SALES_DAT','P20100101','PMAX','DWH_SALES_DATA',10,'Y','DBMAINTUSER',sysdate);
 
INSERT INTO PARTITION_METADATA (OWNER,TABLE_NAME,PARTITION_FREQUENCY,PARTITION_NAME_FORMAT,PARTITION_TS_FORMAT,FIRST_PARTITION_NAME,MAXVAL_PARTITION_NAME,MAXVAL_TS_NAME_FORMAT,NUM_ADVANCE_PARTITIONS,ACTIVE_RECORD_FLAG,DW_UPDATED_BY,DW_LAST_UPDATED)
 VALUES ('DWH','SALES_MONTHLY','MONTHLY','P{yyyy}{mm}','DWH_SALES_DATA','P20100101','PMAX','DWH_SALES_DATA',2,'Y','DBMAINTUSER',sysdate);
 
commit;]

CREATE OR REPLACE package pkg_partition_manager
AS
 PROCEDURE p_create_missing_partitions(
    p_owner      IN partition_metadata.owner%TYPE,
    p_table_name IN partition_metadata.table_name%TYPE
  );
END;
/

